language: php
php:
  - '7.1'
  - '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mail;'
  - mysql -e "CREATE USER 'mail'@'localhost' IDENTIFIED BY 'password';"
  - mysql -e "GRANT ALL PRIVILEGES on mail.* to mail@localhost;"

install:
  - cp phpunit.xml.dist phpunit.xml
  - cp .env.dist .env
  - composer install

script:
  - bin/phpunit
  - bin/behat -f progress
