language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mail_test;'
  - mysql -e "CREATE USER 'mail_test'@'localhost' IDENTIFIED BY 'password';"
  - mysql -e "GRANT ALL PRIVILEGES on mail_test.* to mail_test@localhost;"

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

# try code coverage tests again after updating to php ^7.0
# to slow atm
#script:
#  - bin/phpunit --coverage-clover=coverage.xml
#
#after_success:
#  # Submit coverage report to https://codecov.io
#  - bash <(curl -s https://codecov.io/bash)
