imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: "en" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

sensio_framework_extra:
 router:
     annotations: false

# Twig Configuration
twig:
    exception_controller: AppBundle\Controller\ExceptionController:showAction
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        app_name:     "%app_name%"
        app_url:      "%app_url%"
        project_name: "%project_name%"
        project_url:  "%project_url%"
        domain:       "%domain%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sonata_admin:
    title: Management
    title_logo: 'bundles/app/img/logo_small.png'
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: usrmgmt.admin.block.statistics
    templates:
        layout: 'Admin/standard_layout.html.twig'
        user_block: 'Admin/user_block.html.twig'
    assets:
            # overwrite to remove google fonts
        remove_stylesheets:
            - 'bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css'
        extra_stylesheets:
            - 'bundles/app/css/AdminLTE.min.css'
    security:
        handler: sonata.admin.security.handler.role

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        usrmgmt.admin.block.statistics: ~

sonata_core:
    form:
        mapping:
            enabled: false

mopa_bootstrap:
    menu: ~

nelmio_security:
    csp:
        enabled: true
        enforce:
            default-src:
              - 'none'
            script-src:
              - 'self'
            style-src:
              - 'self'
            font-src:
              - 'self'
            img-src:
              - 'self'
            block-all-mixed-content: true

    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
