imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    spool:
        type: file
        path: "%kernel.cache_dir%/spool"

doctrine:
    dbal:
      dbname:   "%database_name%_test"
      user:     "%database_user%_test"

liip_functional_test:
    command_verbosity: verbose
