services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Builder\WelcomeMessageBuilder:
        arguments:
            $appUrl:       "%app_url%"
            $projectName:  "%project_name%"
            $domain:       "%domain%"

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\EventListener\:
        resource: '../../src/AppBundle/EventListener/*'
        tags:
            - { name: kernel.event_subscriber }

    AppBundle\Handler\:
        resource: '../../src/AppBundle/Handler/*'
        public: true

    AppBundle\Controller\ExceptionController:
        public: true
        arguments:
            $debug: '%kernel.debug%'

    AppBundle\Form\PasswordChangeType:
        tags:
            - { name: form.type, alias: password_change }

    AppBundle\Form\RegistrationType:
        arguments:
            $domain: '%domain%'
        tags:
            - { name: form.type, alias: registration }

    AppBundle\Form\DeleteType:
        tags:
            - { name: form.type, alias: delete }

    AppBundle\Handler\LogoutSuccessHandler:
        arguments:
            $targetUrl: '/'

    AppBundle\Handler\MailHandler:
        arguments:
            $from: "%sender_address%"
            $name: "%app_name%"

    AppBundle\Handler\UserRegistrationInfoHandler:
        arguments:
            $to: "%notification_address%"

    AppBundle\Handler\RegistrationHandler:
        public: true
        arguments:
            $hasSinaBox: "%has_sina_box%"

    AppBundle\Handler\SuspiciousChildrenHandler:
        arguments:
            $to: "%notification_address%"

    AppBundle\Helper\PasswordUpdater:
        public: true

    AppBundle\EventListener\RegistrationListener:
        arguments:
            $sendMail:     "%send_welcome_mail%"

    AppBundle\Menu\MenuBuilder:
        arguments:
            $navbarLeft: '%navbar_left%'

    AppBundle\Security\UserProvider:
        arguments:
            $defaultDomain: "%domain%"

    AppBundle\Sender\WelcomeMessageSender:
        public: true
        arguments:
            $domain:       "%domain%"

    AppBundle\Validator\PasswordPolicyValidator:
        tags:
            - { name: validator.constraint_validator, alias: password_policy }

    AppBundle\Validator\RegistrationValidator:
        arguments:
            $domain: "%domain%"
        tags:
            - { name: validator.constraint_validator, alias: registration }

    AppBundle\Validator\PasswordChangeValidator:
        tags:
            - { name: validator.constraint_validator, alias: password_change }

    AppBundle\Validator\Constraints\EmailDomainValidator:
        tags:
            - { name: validator.constraint_validator }

    usrmgmt.admin.user:
        class: AppBundle\Admin\UserAdmin
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mail", label: "User" }
        arguments:
            - ~
            - AppBundle\Entity\User
            - 'AppBundle:UserCRUD'
        calls:
            - [setPasswordUpdater, ['@AppBundle\Helper\PasswordUpdater']]
            - [setDomainGuesser, ['@AppBundle\Guesser\DomainGuesser']]
            - [setDeleteHandler, ['@AppBundle\Handler\DeleteHandler']]

    usrmgmt.admin.domain:
        class: AppBundle\Admin\DomainAdmin
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mail", label: "Domain" }
        arguments:
            - ~
            - AppBundle\Entity\Domain
            - ~

    usrmgmt.admin.alias:
        class: AppBundle\Admin\AliasAdmin
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mail", label: "Alias" }
        arguments:
            - ~
            - AppBundle\Entity\Alias
            - ~
        calls:
            - [setDomainGuesser, ['@AppBundle\Guesser\DomainGuesser']]

    usrmgmt.admin.voucher:
        class: AppBundle\Admin\VoucherAdmin
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mail", label: "Voucher" }
        arguments:
            - ~
            - AppBundle\Entity\Voucher
            - ~
            - '@Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface'

    usrmgmt.admin.reservedname:
        class: AppBundle\Admin\ReservedNameAdmin
        public: true
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Mail", label: "Reserved Name" }
        arguments:
            - ~
            - AppBundle\Entity\ReservedName
            - ~

    usrmgmt.admin.block.statistics:
        class: AppBundle\Block\StatisticsBlockService
        public: true
        tags:
            - { name: sonata.block }
        arguments:
            - usrmgmt.admin.block.statistics
            - '@Symfony\Component\Templating\EngineInterface'
            - '@Doctrine\Common\Persistence\ObjectManager'
            - '@AppBundle\Counter\UserCounter'
            - '@AppBundle\Counter\VoucherCounter'

    usrmgmt.menu.navbar_left:
        class: Knp\Menu\MenuItem
        public: true
        factory: ['@AppBundle\Menu\MenuBuilder', createNavbarLeft]
        tags:
            - { name: knp_menu.menu, alias: navbar-left }

    usrmgmt.menu.navbar_right:
        class: Knp\Menu\MenuItem
        public: true
        factory: ['@AppBundle\Menu\MenuBuilder', createNavbarRight]
        tags:
            - { name: knp_menu.menu, alias: navbar-right }

    Symfony\Component\Security\Http\HttpUtils:
        alias: security.http_utils

    Knp\Menu\FactoryInterface:
        alias: knp_menu.factory
