- name: ensure mysql is installed
  apt:
    pkg: "{{ item }}"
  with_items:
    - python-mysqldb
    - mysql-server

- name: ensure mysql databases are present
  mysql_db:
    name: "{{ item }}"
  with_items:
    - mail
    - mail_test

- name: ensure mysql user are present
  become: yes
  mysql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: present
  with_items:
    - { user: mail, password: password, priv: "mail.*:ALL" }
    - { user: mail_test, password: password, priv: "mail_test.*:ALL" }
