AppBundle\Entity\ReservedName:
  type: entity
  repositoryClass: AppBundle\Repository\ReservedNameRepository
  table: virtual_reserved_name
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    creationTime:
      #name: creation_time
      type: datetime
      nullable: false
    updatedTime:
      #name: updated_time
      type: datetime
      nullable: false
    name:
      type: string
  lifecycleCallbacks:
    prePersist: [updateCreationTime, updateUpdatedTime]
