---
- name: ensure nginx is installed
  apt:
    pkg: nginx

- name: Change default nginx site
  become: yes
  template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
