App\Entity\OpenPgpKey:
  type: entity
  repositoryClass: App\Repository\OpenPgpKeyRepository
  table: virtual_openpgp_keys
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    email:
      type: string
      nullable: false
      unique: true
    keyId:
      type: text
      nullable: false
    keyFingerprint:
      type: text
      nullable: false
    keyExpireTime:
      type: datetime
      nullable: true
    keyData:
      type: text
      nullable: false
  manyToOne:
    user:
      targetEntity: User
      mappedBy: user_id
      joinColumn:
        name: user_id
        referencedColumnName: id
        nullable: true
